//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExamTaskMitRao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD
    public partial class ExamEntities : DbContext
    {
        public ExamEntities()
            : base("name=ExamEntities")
=======
    public partial class RaoMitEntities : DbContext
    {
        public RaoMitEntities()
            : base("name=RaoMitEntities")
>>>>>>> 9fd577dc6259ea9bd5308c32a72a08f9358d1f21
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public virtual DbSet<ProductMenu> ProductMenus { get; set; }
        public virtual DbSet<ProductMenuItem> ProductMenuItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesProductMenu> RolesProductMenus { get; set; }
=======
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesMenu> RolesMenus { get; set; }
>>>>>>> 9fd577dc6259ea9bd5308c32a72a08f9358d1f21
        public virtual DbSet<RolesUser> RolesUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
