//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExamTaskMitRao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMenu()
        {
            this.ProductMenuItems = new HashSet<ProductMenuItem>();
            this.RolesProductMenus = new HashSet<RolesProductMenu>();
        }
    
        public int productMenuId { get; set; }
        public string menuName { get; set; }
        public string menuItem1 { get; set; }
        public Nullable<int> roleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMenuItem> ProductMenuItems { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesProductMenu> RolesProductMenus { get; set; }
    }
}
